### ISSUE TITLE
NPM 5 - Invalid module name

### ISSUE THREAD

**Issue by roemhildtg** [canjs/can-event-radiochange#6]
When installing a canjs apps dependencies with npm 5, the application appears to install correctly, but steal throws invalid module name when browsing the app. 

![image](https://user-images.githubusercontent.com/5471079/27086029-910b238c-5016-11e7-98fb-e51358c6e080.png)

Rolling back to NPM 4.x resolves the issue.

**Comment by andrejewski** [comment]
Hey @roemhildtg, what Node version are you using? I created a fresh DoneJs app which has the same dependency of `can-stache-bindings` and could not replicate your issue on my npm5. npm5 has been quite buggy for me as well. What I have done is run `npm install --no-shrinkwrap` to circumvent the lockfile business, please let me know if that works for you.

**Comment by roemhildtg** [comment]
I'm not really familiar with the lockfile business, but I tried adding the no shrinkwrap option and ended up with a lot of missing packages. I think for now I'm going to stick with 4.x...

For node I have version 7.10.0 on Windows 7 x64.

**Comment by andrejewski** [comment]
Odd, usually that's what fixes things for me. I'll keep this issue open in case someone has the same problem. Being unable to reproduce there isn't much I can do right now.

**Comment by roemhildtg** [comment]
I'll keep troubleshooting. If I have any info I'll report back.

**Comment by andrejewski** [comment]
👍 Don't spend too much time on it, I expect many npm5 bug fixes in the next few weeks that will probably address our problem.
